---
- name: Install MySQL
  apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
  with_items:
      - mysql-server
      - mysql-client
      - python-mysqldb
      - libmysqlclient-dev
