---
- name: Install PHP
  apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
  with_items:
      - php
      - php-mysql
      - php-gd
      - php-imap
      - php-pear
      - php-xml
      - php-mbstring
      - php-snmp
      - php-soap
      - php-bcmath
      - php-curl
  notify: restart apache
